// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhVJRnCfhSskF3ewuIb5usUwYg9zJf1ZY',
    appId: '1:683855906482:web:b1bee7b478162d45292bab',
    messagingSenderId: '683855906482',
    projectId: 'ambaread-mobile-2025-65007',
    authDomain: 'ambaread-mobile-2025-65007.firebaseapp.com',
    storageBucket: 'ambaread-mobile-2025-65007.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfNkHftMq_WrrMETZMSVRq_MwdhA75-To',
    appId: '1:683855906482:android:001774b65e160274292bab',
    messagingSenderId: '683855906482',
    projectId: 'ambaread-mobile-2025-65007',
    storageBucket: 'ambaread-mobile-2025-65007.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDD3l7a2LbtMxBrhDr92lmiphY3p4e4t9E',
    appId: '1:683855906482:ios:2e3ae9f24dfcffe9292bab',
    messagingSenderId: '683855906482',
    projectId: 'ambaread-mobile-2025-65007',
    storageBucket: 'ambaread-mobile-2025-65007.firebasestorage.app',
    iosBundleId: 'com.example.projectPmob',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDD3l7a2LbtMxBrhDr92lmiphY3p4e4t9E',
    appId: '1:683855906482:ios:2e3ae9f24dfcffe9292bab',
    messagingSenderId: '683855906482',
    projectId: 'ambaread-mobile-2025-65007',
    storageBucket: 'ambaread-mobile-2025-65007.firebasestorage.app',
    iosBundleId: 'com.example.projectPmob',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhVJRnCfhSskF3ewuIb5usUwYg9zJf1ZY',
    appId: '1:683855906482:web:c960f4ab73c6f902292bab',
    messagingSenderId: '683855906482',
    projectId: 'ambaread-mobile-2025-65007',
    authDomain: 'ambaread-mobile-2025-65007.firebaseapp.com',
    storageBucket: 'ambaread-mobile-2025-65007.firebasestorage.app',
  );
}
